name: Deploy SAT Tool

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Authenticate with Databricks
        run: |
          databricks configure --host=${{ secrets.DATABRICKS_URL }} --token=${{ secrets.CLIENT_SECRET }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform/aws

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="databricks_url=${{ secrets.DATABRICKS_URL }}" \
            -var="workspace_id=${{ secrets.WORKSPACE_ID }}" \
            -var="account_console_id=${{ secrets.ACCOUNT_CONSOLE_ID }}" \
            -var="analysis_schema_name=${{ secrets.ANALYSIS_SCHEMA_NAME }}" \
            -var="client_id=${{ secrets.CLIENT_ID }}" \
            -var="client_secret=${{ secrets.CLIENT_SECRET }}" \
            -var="use_sp_auth=${{ secrets.USE_SP_AUTH }}" \
            -var="proxies=${{ secrets.PROXIES }}" \
            -var="run_on_serverless=${{ secrets.RUN_ON_SERVERLESS }}"
        working-directory: ./terraform/aws

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="databricks_url=${{ secrets.DATABRICKS_URL }}" \
            -var="workspace_id=${{ secrets.WORKSPACE_ID }}" \
            -var="account_console_id=${{ secrets.ACCOUNT_CONSOLE_ID }}" \
            -var="analysis_schema_name=${{ secrets.ANALYSIS_SCHEMA_NAME }}" \
            -var="client_id=${{ secrets.CLIENT_ID }}" \
            -var="client_secret=${{ secrets.CLIENT_SECRET }}" \
            -var="use_sp_auth=${{ secrets.USE_SP_AUTH }}" \
            -var="proxies=${{ secrets.PROXIES }}" \
            -var="run_on_serverless=${{ secrets.RUN_ON_SERVERLESS }}"
        working-directory: ./terraform/aws
