name: Deploy SAT Tool

on:
  workflow_dispatch:  # Allows manual execution of the workflow

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Adjust this based on your required Terraform version

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform/aws  # Specify the correct directory

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="databricks_url=${{ secrets.DATABRICKS_URL }}" \
            -var="workspace_id=${{ secrets.WORKSPACE_ID }}" \
            -var="account_console_id=${{ secrets.ACCOUNT_CONSOLE_ID }}" \
            -var="analysis_schema_name=${{ secrets.ANALYSIS_SCHEMA_NAME }}" \
            -var="client_id=${{ secrets.CLIENT_ID }}" \
            -var="client_secret=${{ secrets.CLIENT_SECRET }}" \
            -var="use_sp_auth=true" \
            -var="proxies={}" \
            -var="run_on_serverless=false"
        working-directory: ./terraform/aws  # Set working directory

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="databricks_url=${{ secrets.DATABRICKS_URL }}" \
            -var="workspace_id=${{ secrets.WORKSPACE_ID }}" \
            -var="account_console_id=${{ secrets.ACCOUNT_CONSOLE_ID }}" \
            -var="analysis_schema_name=${{ secrets.ANALYSIS_SCHEMA_NAME }}" \
            -var="client_id=${{ secrets.CLIENT_ID }}" \
            -var="client_secret=${{ secrets.CLIENT_SECRET }}" \
            -var="use_sp_auth=true" \
            -var="proxies={}" \
            -var="run_on_serverless=false"
        working-directory: ./terraform/aws  # Set working directory
