name: Deploy SAT Tool

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read  # Allow GitHub Actions to read repository content

jobs:
  terraform:
    name: Deploy SAT with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="databricks_url=${{ secrets.DATABRICKS_URL }}" \
            -var="workspace_id=${{ secrets.WORKSPACE_ID }}" \
            -var="account_console_id=${{ secrets.ACCOUNT_CONSOLE_ID }}" \
            -var="analysis_schema_name=${{ secrets.ANALYSIS_SCHEMA_NAME }}" \
            -var="client_id=${{ secrets.CLIENT_ID }}" \
            -var="client_secret=${{ secrets.CLIENT_SECRET }}" \
            -var="use_sp_auth=true" \
            -var="proxies={}" \
            -var="run_on_serverless=false"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="databricks_url=${{ secrets.DATABRICKS_URL }}" \
            -var="workspace_id=${{ secrets.WORKSPACE_ID }}" \
            -var="account_console_id=${{ secrets.ACCOUNT_CONSOLE_ID }}" \
            -var="analysis_schema_name=${{ secrets.ANALYSIS_SCHEMA_NAME }}" \
            -var="client_id=${{ secrets.CLIENT_ID }}" \
            -var="client_secret=${{ secrets.CLIENT_SECRET }}" \
            -var="use_sp_auth=true" \
            -var="proxies={}" \
            -var="run_on_serverless=false"
