name: Deploy SAT Tool

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Export Secrets as Environment Variables
        run: |
          echo "TF_VAR_databricks_url=${{ secrets.DATABRICKS_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_workspace_id=${{ secrets.WORKSPACE_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_account_console_id=${{ secrets.ACCOUNT_CONSOLE_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_analysis_schema_name=${{ secrets.ANALYSIS_SCHEMA_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_client_id=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_client_secret=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_use_sp_auth=${{ secrets.USE_SP_AUTH }}" >> $GITHUB_ENV
          echo "TF_VAR_proxies=${{ secrets.PROXIES }}" >> $GITHUB_ENV
          echo "TF_VAR_run_on_serverless=${{ secrets.RUN_ON_SERVERLESS }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform/aws

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform/aws

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/aws
