name: Destroy SAT Tool

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read

jobs:
  terraform-destroy:
    name: Run Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure Databricks Authentication
        run: |
          echo "DATABRICKS_HOST=${{ secrets.databricks_url }}" >> $GITHUB_ENV
          echo "DATABRICKS_CLIENT_ID=${{ secrets.client_id }}" >> $GITHUB_ENV
          echo "DATABRICKS_CLIENT_SECRET=${{ secrets.client_secret }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
          cd terraform/aws
          terraform init

      - name: Run Terraform Destroy
        run: |
          cd terraform/aws
          terraform destroy -auto-approve
