name: Destroy SAT Deployment

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure environment variables
        run: |
          echo "TF_VAR_account_console_id=${{ secrets.ACCOUNT_CONSOLE_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_analysis_schema_name=${{ secrets.ANALYSIS_SCHEMA_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_client_id=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_client_secret=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_databricks_url=${{ secrets.DATABRICKS_URL }}" >> $GITHUB_ENV
          echo "TF_VAR_proxies=${{ secrets.PROXIES }}" >> $GITHUB_ENV
          echo "TF_VAR_run_on_serverless=${{ secrets.RUN_ON_SERVERLESS }}" >> $GITHUB_ENV
          echo "TF_VAR_use_sp_auth=${{ secrets.USE_SP_AUTH }}" >> $GITHUB_ENV
          echo "TF_VAR_workspace_id=${{ secrets.WORKSPACE_ID }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
          cd terraform/aws
          terraform init

      - name: Destroy Terraform Infrastructure
        run: |
          cd terraform/aws
          terraform destroy -auto-approve
